#!/usr/bin/env python3

#    Copyright 2025 Cameron Brock

#    This file is part of MotivateMe.

#    MotivateMe is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

#    MotivateMe is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License along with MotivateMe. If not, see <https://www.gnu.org/licenses/>. 

# Imports
from utils.output_formatting.prettybox import print_msg
from utils.getrandquote import getrandquote
import math
import os
import sys

# Add the directory of this file to sys.path, which Python uses
# to search for modules.
dirname = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, dirname)

# Get a random quote from the list of quotes.
quote = getrandquote()

# Output the quote using print_msg.
print_msg(quote["quote"], quote["author"], 50)

